[build-system]
requires = ["hatchling>=1.10.0"]
build-backend = "hatchling.build"

[project]
name = "soniox"
version = "2.3.0"
dependencies = ["httpx>0.25.0", "websockets>11.0", "pydantic>2"]
requires-python = ">=3.10"
authors = [{ name = "Soniox", email = "support@soniox.com" }]
maintainers = [{ name = "Soniox", email = "support@soniox.com" }]
description = "The official Python SDK for the Soniox API (STT, REST)"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["soniox", "speech-to-text", "stt", "ai", "sdk"]
classifiers = [
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Operating System :: POSIX",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: Apache Software License",
]

[project.urls]
Homepage = "https://sonoix.com"
Documentation = "https://soniox.com/docs"
Repository = "https://github.com/soniox/soniox-python"

[project.optional-dependencies]
dev = ["ruff>=0.0.0", "pyright>=1.1.0", "griffe>=1.15.0"]

[tool.hatch.build.targets.wheel]
packages = ["src/soniox"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "W", "F", "I", "C", "B", "UP"]
ignore = ["E501", "B008", "C901"]
exclude = ["build", "dist", ".venv", "tests"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pyright]
include = ["src"]
venvPath = "."
venv = ".venv"
exclude = ["build", "dist", ".venv"]
typeCheckingMode = "strict"
reportMissingImports = true
pythonVersion = "3.10"
